### PR TITLE
mraa/UPM: update recipes to meta-oe master, bump up versions

### PR DESCRIPTION
**Pull request by alext-mkrs**
mraa/UPM NodeJS bindings part 2 - recipes themselves.

### CODE REVIEW

**Comment by alext-mkrs** [comment]
Having to get through forks to be able to send PRs proves to be quite ineffective - I in fact have to maintain a second copy of all repos involved, just to make and push commits. It would be more efficient to maybe setup a separate GH organization to keep those repos in and add me as a collaborator, so that I could send PRs using local branches, that way I would be able to use the same physical repo both for development and submissions. Or do the same in your current repos, not a separate org. I understand you may want to first build some trust before doing that though :)

**Comment by htot** [comment]
I have been removing recipes from iot-middleware as I found newer ones on oe. And I agree it's inconvenient this way. Mraa and upm will probably get removed too at some point as we move to rocko or further. We could empty this layer and move the useful stuff to intel-edison? There is already bsp and distro, we could create middleware there?
I wouldn't mind creating an organization or add you as a collaborator to this repo. Just not sure how to do that. And how do these local branches work? Actually now I have similar inefficiencies, to test your PR I need to clone you, or create a tracking branch. I am open to suggestions for an efficient work flow. You probably read on the wiki page writing sw is not my specialty (designing intrinsically safe electronics is) and I'm new to Yocto.

**Comment by alext-mkrs** [comment]
As for the layer, I'm all hands for picking out those recipes we're intetested in and putting them into -edison, this layer is deprecated anyway. If its only mraa and upm we want from this one, even more so - we can pull them to -edison for now and with rocko they'll be in meta-oe.

As for the org/repos, actually never mind - I should have just started with forks as the basis for my build  not with direct clones, but I'll fix that at my end. For you to check the PRs out, there's a GH help article about checking out PRs as branches for local testing, quite handy - just google that and it should pop up. Let me know if not, I'll help you find it.

And yeah, I've checked Exalon website - interesting stuff :-)

**Comment by htot** [comment]
Allright, so this is what I should do: take your PR, move middleware to intel-edison, drop a text file in the empty dir to explain where everything went, that will be the final commit for this branch. Update the layer in intel-edison. Try your patch for intel-edison mraa/upm. Maybe tomorrow.

**Comment by htot** [comment]
Merged, thanks

**Pull request merged**
